export { ReactComponent as YearIco } from './yearIco.svg'
export { ReactComponent as MonthIco } from './monthIco.svg'
export { ReactComponent as WeekIco } from './weekIco.svg'
export { ReactComponent as DayIco } from './dayIco.svg'
export { ReactComponent as KebabMenuIco } from './kebabMenu.svg'
export { ReactComponent as ArrowIco } from './arrowIco.svg'